doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'sqlsrv'
                charset: UTF-8
                options:
                    TrustServerCertificate: yes
                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_URL env var (see .env file)
                #server_version: '13'
            # ugouv:
            #     url: '%env(resolve:DATABASE_URL_UGOUV)%'
            #     driver: 'mysql'
            #     charset: UTF-8
            #     IMPORTANT: You MUST configure your server version,
            #     either here or in the DATABASE_URL env var (see .env file)
            #     server_version: '5.7'
            # HosixHcz:
            #     # configure these for your database server
            #     url: '%env(resolve:DATABASE_URL_Hosix_Hcz)%'
            #     driver: 'sqlsrv'
            #     charset: UTF-8
            #     options:
            #         TrustServerCertificate: yes
            # TLIMS:
            #     # configure these for your database server
            #     url: '%env(resolve:DATABASE_URL_TLIMS)%'
            #     driver: 'sqlsrv'
            #     charset: UTF-8
            #     options:
            #         TrustServerCertificate: yes
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            # ugouv:
            #     connection: ugouv
            # HosixHcz:
            #     connection: HosixHcz
            # TLIMS:
            #     connection: TLIMS
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
